version: "3"
services:
  myportfolio:
    build: .
    restart: always
    env_file: .env
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
