version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

  myportfolio:
    build: .
    depends_on:
      - mysql
    expose:
      - "5001"
    command: python3 -m app
    env_file: .env
    environment:
      - MYSQL_HOST=mysql
    restart: always

  nginx:
    image: docker.io/jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: aceleagueoflegends@gmail.com
      NGINX_SERVER_NAME: ace-perez-portfolio.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - nginx_certbot_www:/var/www/certbot
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
  nginx_certbot_www: